using System;
using System.Collections.Generic;
using System.Globalization;
using System.IO;
using System.Text;
using Microsoft.Kinect;

namespace KinectReframe.Services
{
    public static class PointCloudExporter
    {
        private struct Vertex
        {
            public float X;
            public float Y;
            public float Z;
            public byte Red;
            public byte Green;
            public byte Blue;
        }

        public static int ExportPly(
            string path,
            DepthImagePixel[] depthPixels,
            SkeletonPoint[] cameraPoints,
            bool bodyOnly,
            int sampleStep)
        {
            if (string.IsNullOrWhiteSpace(path))
            {
                throw new ArgumentException("An export path is required.", "path");
            }

            if (depthPixels == null)
            {
                throw new ArgumentNullException("depthPixels");
            }

            if (cameraPoints == null)
            {
                throw new ArgumentNullException("cameraPoints");
            }

            if (depthPixels.Length != cameraPoints.Length)
            {
                throw new ArgumentException("Depth and camera-space buffers must have the same length.");
            }

            sampleStep = Math.Max(1, sampleStep);
            List<Vertex> vertices = new List<Vertex>(depthPixels.Length / (sampleStep * sampleStep));

            const int sourceWidth = 320;
            const int sourceHeight = 240;
            for (int y = 0; y < sourceHeight; y += sampleStep)
            {
                int rowOffset = y * sourceWidth;
                for (int x = 0; x < sourceWidth; x += sampleStep)
                {
                    int index = rowOffset + x;
                    DepthImagePixel depthPixel = depthPixels[index];
                    if (depthPixel.Depth <= 0 || (bodyOnly && depthPixel.PlayerIndex <= 0))
                    {
                        continue;
                    }

                    SkeletonPoint point = cameraPoints[index];
                    if (point.Z <= 0.15f || float.IsNaN(point.X) || float.IsNaN(point.Y) || float.IsNaN(point.Z))
                    {
                        continue;
                    }

                    byte red;
                    byte green;
                    byte blue;
                    SelectColour(depthPixel, point.Z, out red, out green, out blue);
                    vertices.Add(new Vertex
                    {
                        X = point.X,
                        Y = point.Y,
                        Z = point.Z,
                        Red = red,
                        Green = green,
                        Blue = blue
                    });
                }
            }

            string directory = Path.GetDirectoryName(path);
            if (!string.IsNullOrWhiteSpace(directory))
            {
                Directory.CreateDirectory(directory);
            }

            CultureInfo invariant = CultureInfo.InvariantCulture;
            using (StreamWriter writer = new StreamWriter(path, false, new UTF8Encoding(false)))
            {
                writer.WriteLine("ply");
                writer.WriteLine("format ascii 1.0");
                writer.WriteLine("comment generated by Kinect Reframe");
                writer.WriteLine("element vertex " + vertices.Count.ToString(invariant));
                writer.WriteLine("property float x");
                writer.WriteLine("property float y");
                writer.WriteLine("property float z");
                writer.WriteLine("property uchar red");
                writer.WriteLine("property uchar green");
                writer.WriteLine("property uchar blue");
                writer.WriteLine("end_header");

                foreach (Vertex vertex in vertices)
                {
                    writer.Write(vertex.X.ToString("R", invariant));
                    writer.Write(' ');
                    writer.Write(vertex.Y.ToString("R", invariant));
                    writer.Write(' ');
                    writer.Write(vertex.Z.ToString("R", invariant));
                    writer.Write(' ');
                    writer.Write(vertex.Red.ToString(invariant));
                    writer.Write(' ');
                    writer.Write(vertex.Green.ToString(invariant));
                    writer.Write(' ');
                    writer.WriteLine(vertex.Blue.ToString(invariant));
                }
            }

            return vertices.Count;
        }

        private static void SelectColour(
            DepthImagePixel depthPixel,
            double depthMetres,
            out byte red,
            out byte green,
            out byte blue)
        {
            if (depthPixel.PlayerIndex > 0)
            {
                double brightness = Math.Max(0.45, Math.Min(1.0, 1.25 - (depthMetres * 0.16)));
                red = (byte)(55 * brightness);
                green = (byte)(235 * brightness);
                blue = (byte)(255 * brightness);
                return;
            }

            double normalized = Math.Max(0.0, Math.Min(1.0, (depthMetres - 0.5) / 3.8));
            red = (byte)(38 + (160 * normalized));
            green = (byte)(210 - (110 * normalized));
            blue = (byte)(255 - (70 * normalized));
        }
    }
}
